### ISSUE TITLE
Dodać resolver generateInviteToken

### ISSUE THREAD

**Issue by aexol** [graphql-editor/gei-users#3]
Dodać resolver do generateInvite token z opcjonalną datą wygaśnięcie i domeną na którą musi kończyć się username:

np. `@aexol.com`

oczwiście `expired` oraz `domain` opcjonalne.  Potrzebne będzie też opcjonalne pole w register input invitationToken.

Wtedy w integracji potrzebne będzie też query do Team members itd.

**Comment by TakSeBiegam** [comment]
jak zrozumiałem ten inviteToken jest tylko podczas rejestracji czy działa też jeżeli użytkownik posiada konto ?

**Comment by aexol** [comment]
tylko podczas rejestracji jest to, tak naprawdę doklejane do linka, by dało się zapraszać ludzi linkiem jak na discordzie
