### ISSUE TITLE
Rejestracja usera z githubem po emailu a nie nazwie użytkownika

### ISSUE THREAD

**Issue by Matnabru** [graphql-editor/gei-users#36]

**Comment by AleksanderBondar** [comment]
I teraz tak, może dorobić jakieś powiadomienie że jak user ma konto założone googlem, i potem loguje się na ten konto czyli mam email -> aleksanderbondar98@gmail.com -> zalogowałem się na ten email tak więc powstał User na tego emaila, no i teraz zakładamy case, że user zapomniał po miesiącu że założył konto googlem i próbuje usilnie założyć konto albo zalogować się na email aleksanderbondar98@gmail.com -> zwróćmy mu informacje "You provided other method of login on this email" ?

**Comment by AleksanderBondar** [comment]
Co w casie gdy user zakłada konto jakimś (oauthem) a potem zrobi change password? Powinniśmy całkowicie zablokować tą opcję dla userów założonych przez oauth ( to samo z forgot password )

**Comment by Matnabru** [comment]
Ok dodane

**Comment by Matnabru** [comment]
Można by było na przyszłość dodać coś w stylu ustawiania haseł dla userów ktorzy mają integracje jedynie przez oautha
Bo teraz można założyć normalne konto i dodać do niego ouath, ale na odwrót już nie
